trigger:
  branches:
    include:
      - main
      - develop

pool: WinPool

variables:
  solution: '**/ConsultersIT.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self
  clean: true

- script: |
    ls -lR $(Build.SourcesDirectory)
    cat $(Build.SourcesDirectory)/ConsultersIT.sln
  displayName: 'List files and show .sln content'

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration)'