trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/ConsultersIT.sln'  # Específico em vez de genérico
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self
  clean: true

- powershell: |
    # Verificação robusta do arquivo .sln
    $slnPath = "$(Build.SourcesDirectory)\ConsultersIT.sln"
    if (-not (Test-Path $slnPath)) {
        Write-Host "##vso[task.logissue type=error]Arquivo .sln não encontrado em $slnPath"
        exit 1
    }
    $content = Get-Content $slnPath -Raw
    if (-not $content.StartsWith("Microsoft Visual Studio Solution File")) {
        Write-Host "##vso[task.logissue type=error]Arquivo .sln inválido ou corrompido"
        exit 1
    }
    Write-Host "Arquivo .sln válido encontrado"
  displayName: 'Validate solution file'

- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet Packages'
  inputs:
    command: 'restore'
    projects: '**/ConsultersIT.sln'
    feedsToUse: 'select'

- task: VSBuild@1
  inputs:
    solution: '**/ConsultersIT.sln'
    platform: 'Any CPU'
    configuration: 'Release'